### ISSUE TITLE
iOS crash when stop recording

### ISSUE THREAD

**Issue by alperenbaskaya58** [endmr11/ed_screen_recorder#1]
Hi, I am trying to record screen. but it crashes when stop recording. 

`flutter:       >>> Start Record Response Output:
flutter:       File: File: '[/Users/alperenbaskaya/Library/Developer/CoreSimulator/Devices/971548E6-9EDD-42FD-84E8-8DDBFFC2CAB7/data/Containers/Data/Application/126FFC94-020B-4C4A-80C1-F368F5905C5C/Documents/Eren.mp4]()'
flutter:       Event Name: startRecordScreen
flutter:       Progressing: true
flutter:       Message: Started Video
flutter:       Success: false
flutter:       Video Hash: 14c316a0bf1911ec9c27f365359d878d
flutter:       Start Date: 1650287498508
flutter:       End Date: 0
flutter:
Lost connection to device.`

**Comment by alperenbaskaya58** [comment]
*2022-04-18 16:24:45.904448+0300 Runner[61042:34975612] Metal API
Validation Enabled*

*2022-04-18 16:24:46.272360+0300 Runner[61042:34977997] [WindowServer]
display_timer_callback: unexpected state (now:47aa0a6c425a8 <
expected:47aa0a7b17208)*

*2022-04-18 16:24:46.825135+0300 Runner[61042:34978036] flutter:
Observatory listening on http://127.0.0.1:49572/xiZks_ed8sk=/
<http://127.0.0.1:49572/xiZks_ed8sk=/>*

*2022-04-18 16:24:47.011806+0300 Runner[61042:34975612] -[UIWindow
endDisablingInterfaceAutorotationAnimated:] called on <UIWindow:
0x7fa936c61f80; frame = (0 0; 414 736); gestureRecognizers = <NSArray:
0x6000012e4630>; layer = <UIWindowLayer: 0x600001c78ae0>> without matching
-beginDisablingInterfaceAutorotation. Ignoring.*

*2022-04-18 16:24:48.659821+0300 Runner[61042:34977998] Errors found!
Invalidating cache...*

*2022-04-18 16:24:49.036421+0300 Runner[61042:34977998] Errors found!
Invalidating cache...*

*2022-04-18 16:24:54.991911+0300 Runner[61042:34975612] startRecording: w x
h = 1242 x 2208 pixels*

*2022-04-18 16:24:55.535398+0300 Runner[61042:34977997] flutter:       >>>
Start Record Response Output:*

*2022-04-18 16:24:55.535863+0300 Runner[61042:34977997] flutter:
File: File:
'/Users/alperenbaskaya/Library/Developer/CoreSimulator/Devices/971548E6-9EDD-42FD-84E8-8DDBFFC2CAB7/data/Containers/Data/Application/6967DDE0-C635-46E3-BA10-758E51FF23D3/Documents/Eren.mp4'*

*2022-04-18 16:24:55.535956+0300 Runner[61042:34977997] flutter:
Event Name: startRecordScreen*

*2022-04-18 16:24:55.536024+0300 Runner[61042:34977997] flutter:
Progressing: true*

*2022-04-18 16:24:55.536121+0300 Runner[61042:34977997] flutter:
Message: Started Video*

*2022-04-18 16:24:55.536226+0300 Runner[61042:34977997] flutter:
Success: false*

*2022-04-18 16:24:55.536311+0300 Runner[61042:34977997] flutter:
Video Hash: ef7945c0bf1a11ec8aca232e7f071706*

*2022-04-18 16:24:55.536371+0300 Runner[61042:34977997] flutter:
Start Date: 1650288295489*

*2022-04-18 16:24:55.536447+0300 Runner[61042:34977997] flutter:       End
Date: 0*

*2022-04-18 16:24:55.536509+0300 Runner[61042:34977997] flutter:*

*Stopping recording...*

*2022-04-18 16:25:05.919995+0300 Runner[61042:34975612] *** Terminating app
due to uncaught exception 'NSInternalInconsistencyException', reason: '***
-[AVAssetWriterInput markAsFinished] Cannot call method when status is 0'*

**** First throw call stack:*

*(*

* 0   CoreFoundation                      0x0000000109bd7fba
__exceptionPreprocess + 242*

* 1   libobjc.A.dylib                     0x0000000109a8cff5
objc_exception_throw + 48*

* 2   AVFCore                             0x0000000121e79e16
-[AVAssetWriterInputHelper markCurrentPassAsFinished] + 0*

* 3   AVFCore                             0x0000000121e751c7
-[AVAssetWriterInput markAsFinished] + 135*

* 4   ed_screen_recorder                  0x0000000109495c40
$s18ed_screen_recorder27SwiftEdScreenRecorderPluginC13stopRecordingSbyF +
816*

* 5   ed_screen_recorder                  0x0000000109490723
$s18ed_screen_recorder27SwiftEdScreenRecorderPluginC6handle_6resultySo17FlutterMethodCallC_yypSgctF
+ 9475*

* 6   ed_screen_recorder                  0x000000010949214e
$s18ed_screen_recorder27SwiftEdScreenRecorderPluginC6handle_6resultySo17FlutterMethodCallC_yypSgctFTo
+ 142*

* 7   Flutter                             0x000000010a829571
__45-[FlutterMethodChannel setMethodCallHandler:]_block_invoke + 104*

* 8   Flutter                             0x000000010a2b86df
_ZNK7flutter21PlatformMessageRouter21HandlePlatformMessageENSt3__110unique_ptrINS_15PlatformMessageENS1_14default_deleteIS3_EEEE
+ 193*

* 9   Flutter                             0x000000010a2bddf9
_ZN7flutter15PlatformViewIOS21HandlePlatformMessageENSt3__110unique_ptrINS_15PlatformMessageENS1_14default_deleteIS3_EEEE
+ 35*

* 10  Flutter                             0x000000010a6fe09b
_ZNSt3__110__function6__funcIN3fml8internal14CopyableLambdaIZN7flutter5Shell29OnEngineHandlePlatformMessageENS_10unique_ptrINS5_15PlatformMessageENS_14default_deleteIS8_EEEEE4$_15EENS_9allocatorISD_EEFvvEEclEv
+ 81*

* 11  Flutter                             0x000000010a5fdef0
_ZN3fml15MessageLoopImpl10FlushTasksENS_9FlushTypeE + 164*

* 12  Flutter                             0x000000010a604324
_ZN3fml17MessageLoopDarwin11OnTimerFireEP16__CFRunLoopTimerPS0_ + 26*

* 13  CoreFoundation                      0x0000000109b4678a
__CFRUNLOOP_IS_CALLING_OUT_TO_A_TIMER_CALLBACK_FUNCTION__ + 20*

* 14  CoreFoundation                      0x0000000109b4627c
__CFRunLoopDoTimer + 924*

* 15  CoreFoundation                      0x0000000109b4581a
__CFRunLoopDoTimers + 265*

* 16  CoreFoundation                      0x0000000109b3fe69 __CFRunLoopRun
+ 2013*

* 17  CoreFoundation                      0x0000000109b3f1a7
CFRunLoopRunSpecific + 567*

* 18  GraphicsServices                    0x0000000111097d85
GSEventRunModal + 139*

* 19  UIKitCore                           0x00000001170704df
-[UIApplication _run] + 912*

* 20  UIKitCore                           0x000000011707539c
UIApplicationMain + 101*

* 21  Runner                              0x0000000100f150eb main + 75*

* 22  libdyld.dylib                       0x000000010fbf1bbd start + 1*

*)*

*libc++abi: terminating with uncaught exception of type NSException*

*** Terminating app due to uncaught exception
'NSInternalInconsistencyException', reason: '*** -[AVAssetWriterInput
markAsFinished] Cannot call method when status is 0'

terminating with uncaught exception of type NSException

CoreSimulator 757.5 - Device: iPhone 8 Plus
(971548E6-9EDD-42FD-84E8-8DDBFFC2CAB7) - Runtime: iOS 14.5 (18E182) -
DeviceType: iPhone 8 Plus

**Comment by alperenbaskaya58** [comment]
önceki maile ekledim, mic ve diğer izni de talep etmiştim aslında.

**Comment by endmr11** [comment]
Gerçek bir IOS cihazında deniyorsunuz değil mi? Çünkü Emulator
desteklemiyor.

alperenbaskaya58 ***@***.***>, 18 Nis 2022 Pzt, 16:27
tarihinde şunu yazdı:

> önceki maile ekledim, mic ve diğer izni de talep etmiştim aslında.
>
>
> On Mon, 18 Apr 2022 at 16:26, Alperen Baskaya ***@***.***>
> wrote:
>
> > *2022-04-18 16:24:45.904448+0300 Runner[61042:34975612] Metal API
> > Validation Enabled*
> >
> > *2022-04-18 16:24:46.272360+0300 Runner[61042:34977997] [WindowServer]
> > display_timer_callback: unexpected state (now:47aa0a6c425a8 <
> > expected:47aa0a7b17208)*
> >
> > *2022-04-18 16:24:46.825135+0300 Runner[61042:34978036] flutter:
> > Observatory listening on http://127.0.0.1:49572/xiZks_ed8sk=/
> > <http://127.0.0.1:49572/xiZks_ed8sk=/>*
> >
> > *2022-04-18 16:24:47.011806+0300 Runner[61042:34975612] -[UIWindow
> > endDisablingInterfaceAutorotationAnimated:] called on <UIWindow:
> > 0x7fa936c61f80; frame = (0 0; 414 736); gestureRecognizers = <NSArray:
> > 0x6000012e4630>; layer = <UIWindowLayer: 0x600001c78ae0>> without
> matching
> > -beginDisablingInterfaceAutorotation. Ignoring.*
> >
> > *2022-04-18 16:24:48.659821+0300 Runner[61042:34977998] Errors found!
> > Invalidating cache...*
> >
> > *2022-04-18 16:24:49.036421+0300 Runner[61042:34977998] Errors found!
> > Invalidating cache...*
> >
> > *2022-04-18 16:24:54.991911+0300 Runner[61042:34975612] startRecording: w
> > x h = 1242 x 2208 pixels*
> >
> > *2022-04-18 16:24:55.535398+0300 Runner[61042:34977997] flutter: >>>
> > Start Record Response Output:*
> >
> > *2022-04-18 16:24:55.535863+0300 Runner[61042:34977997] flutter:
> > File: File:
> >
> '/Users/alperenbaskaya/Library/Developer/CoreSimulator/Devices/971548E6-9EDD-42FD-84E8-8DDBFFC2CAB7/data/Containers/Data/Application/6967DDE0-C635-46E3-BA10-758E51FF23D3/Documents/Eren.mp4'*
> >
> > *2022-04-18 16:24:55.535956+0300 Runner[61042:34977997] flutter:
> > Event Name: startRecordScreen*
> >
> > *2022-04-18 16:24:55.536024+0300 Runner[61042:34977997] flutter:
> > Progressing: true*
> >
> > *2022-04-18 16:24:55.536121+0300 Runner[61042:34977997] flutter:
> > Message: Started Video*
> >
> > *2022-04-18 16:24:55.536226+0300 Runner[61042:34977997] flutter:
> > Success: false*
> >
> > *2022-04-18 16:24:55.536311+0300 Runner[61042:34977997] flutter:
> > Video Hash: ef7945c0bf1a11ec8aca232e7f071706*
> >
> > *2022-04-18 16:24:55.536371+0300 Runner[61042:34977997] flutter:
> > Start Date: 1650288295489*
> >
> > *2022-04-18 16:24:55.536447+0300 Runner[61042:34977997] flutter: End
> > Date: 0*
> >
> > *2022-04-18 16:24:55.536509+0300 Runner[61042:34977997] flutter:*
> >
> > *Stopping recording...*
> >
> > *2022-04-18 16:25:05.919995+0300 Runner[61042:34975612] *** Terminating
> > app due to uncaught exception 'NSInternalInconsistencyException', reason:
> > '*** -[AVAssetWriterInput markAsFinished] Cannot call method when status
> is
> > 0'*
> >
> > **** First throw call stack:*
> >
> > *(*
> >
> > * 0 CoreFoundation 0x0000000109bd7fba
> > __exceptionPreprocess + 242*
> >
> > * 1 libobjc.A.dylib 0x0000000109a8cff5
> > objc_exception_throw + 48*
> >
> > * 2 AVFCore 0x0000000121e79e16
> > -[AVAssetWriterInputHelper markCurrentPassAsFinished] + 0*
> >
> > * 3 AVFCore 0x0000000121e751c7
> > -[AVAssetWriterInput markAsFinished] + 135*
> >
> > * 4 ed_screen_recorder 0x0000000109495c40
> > $s18ed_screen_recorder27SwiftEdScreenRecorderPluginC13stopRecordingSbyF +
> > 816*
> >
> > * 5 ed_screen_recorder 0x0000000109490723
> >
> $s18ed_screen_recorder27SwiftEdScreenRecorderPluginC6handle_6resultySo17FlutterMethodCallC_yypSgctF
> > + 9475*
> >
> > * 6 ed_screen_recorder 0x000000010949214e
> >
> $s18ed_screen_recorder27SwiftEdScreenRecorderPluginC6handle_6resultySo17FlutterMethodCallC_yypSgctFTo
> > + 142*
> >
> > * 7 Flutter 0x000000010a829571
> > __45-[FlutterMethodChannel setMethodCallHandler:]_block_invoke + 104*
> >
> > * 8 Flutter 0x000000010a2b86df
> >
> _ZNK7flutter21PlatformMessageRouter21HandlePlatformMessageENSt3__110unique_ptrINS_15PlatformMessageENS1_14default_deleteIS3_EEEE
> > + 193*
> >
> > * 9 Flutter 0x000000010a2bddf9
> >
> _ZN7flutter15PlatformViewIOS21HandlePlatformMessageENSt3__110unique_ptrINS_15PlatformMessageENS1_14default_deleteIS3_EEEE
> > + 35*
> >
> > * 10 Flutter 0x000000010a6fe09b
> >
> _ZNSt3__110__function6__funcIN3fml8internal14CopyableLambdaIZN7flutter5Shell29OnEngineHandlePlatformMessageENS_10unique_ptrINS5_15PlatformMessageENS_14default_deleteIS8_EEEEE4$_15EENS_9allocatorISD_EEFvvEEclEv
> > + 81*
> >
> > * 11 Flutter 0x000000010a5fdef0
> > _ZN3fml15MessageLoopImpl10FlushTasksENS_9FlushTypeE + 164*
> >
> > * 12 Flutter 0x000000010a604324
> > _ZN3fml17MessageLoopDarwin11OnTimerFireEP16__CFRunLoopTimerPS0_ + 26*
> >
> > * 13 CoreFoundation 0x0000000109b4678a
> > __CFRUNLOOP_IS_CALLING_OUT_TO_A_TIMER_CALLBACK_FUNCTION__ + 20*
> >
> > * 14 CoreFoundation 0x0000000109b4627c
> > __CFRunLoopDoTimer + 924*
> >
> > * 15 CoreFoundation 0x0000000109b4581a
> > __CFRunLoopDoTimers + 265*
> >
> > * 16 CoreFoundation 0x0000000109b3fe69
> > __CFRunLoopRun + 2013*
> >
> > * 17 CoreFoundation 0x0000000109b3f1a7
> > CFRunLoopRunSpecific + 567*
> >
> > * 18 GraphicsServices 0x0000000111097d85
> > GSEventRunModal + 139*
> >
> > * 19 UIKitCore 0x00000001170704df
> > -[UIApplication _run] + 912*
> >
> > * 20 UIKitCore 0x000000011707539c
> > UIApplicationMain + 101*
> >
> > * 21 Runner 0x0000000100f150eb main + 75*
> >
> > * 22 libdyld.dylib 0x000000010fbf1bbd start + 1*
> >
> > *)*
> >
> > *libc++abi: terminating with uncaught exception of type NSException*
> >
> > *** Terminating app due to uncaught exception
> > 'NSInternalInconsistencyException', reason: '*** -[AVAssetWriterInput
> > markAsFinished] Cannot call method when status is 0'
> >
> > terminating with uncaught exception of type NSException
> >
> > CoreSimulator 757.5 - Device: iPhone 8 Plus
> > (971548E6-9EDD-42FD-84E8-8DDBFFC2CAB7) - Runtime: iOS 14.5 (18E182) -
> > DeviceType: iPhone 8 Plus
> >

**Comment by alperenbaskaya58** [comment]
teşekküler
