### ISSUE TITLE
First frames black

### ISSUE THREAD

**Issue by jaboyc** [endmr11/ed_screen_recorder#10]
The first couple frames of the video are black. This makes it so the preview of the video in the Photos App is completely black instead of a frame from my Flutter app.

**Comment by endmr11** [comment]
What is the device model under test?

**Comment by jaboyc** [comment]
Please excuse this, I made a mistake, my video player was creating black preview frames, the videos generated are fine. Need more coffee ☕️

**Comment by endmr11** [comment]
It's okay my friend. We are developing together. :)
