### ISSUE TITLE
Pause and Resume Video Feature was there in HBiSoft Plugin, but not in this Flutter Plugin

### ISSUE THREAD

**Issue by hemandroid** [endmr11/ed_screen_recorder#14]
Hi there,

I was using this plugin and we have the requirement of pause the video and resume the video. When can we have that feature available in the Plugin. Is there any possibility to enable and disable the Audio record option, after initiating the startRecord() function.

Please do let me know asap.

**Comment by endmr11** [comment]
This feature will be added as soon as possible. Don't worry. Have a nice day.

**Comment by endmr11** [comment]
Feature added. Please check :)
