### ISSUE TITLE
Audi recording is not working for me (internal & external)

### ISSUE THREAD

**Issue by LakshanKodithuwakku** [endmr11/ed_screen_recorder#16]
My device is a Redmi note 9 pro
I have given permission for a mic for the app on my mobile 
given permission to record audio on AndroidManifest.xml also

**Comment by LakshanKodithuwakku** [comment]
My device is a Redmi note 9 pro
I have given permission for a mic for the app on my mobile 
given permission to record audio on AndroidManifest.xml also

**Comment by endmr11** [comment]
The phone does not record sound from the microphone.
