### ISSUE TITLE
Change path

### ISSUE THREAD

**Issue by DanteAlucard98** [endmr11/ed_screen_recorder#3]
Hello i have a question i proved your screen recorder and it's amazing, but when i stop Record the video is saved in cache, and i would like to know if the path could be changed, and how.

Thanks

**Comment by endmr11** [comment]
This feature will be added as soon as possible. Don't worry. Have a nice day.

**Comment by endmr11** [comment]
Added Custom File Path - Directory feature. Can you please test it? @linnminhtet23 @DanteAlucard98

**Comment by DanteAlucard98** [comment]
Thanks, i test it and wooow awesome :3
