### ISSUE TITLE
Can't build in release mode 

### ISSUE THREAD

**Issue by GorIvanov** [endmr11/ed_screen_recorder#37]
Execution failed for task ':ed_screen_recorder:verifyReleaseResources'.
> A failure occurred while executing com.android.build.gradle.tasks.VerifyLibraryResourcesTask$Action
   > Android resource linking failed
     ERROR:C:\_\_\.gradle\caches\transforms-3\5e083c06c9925c2309f02468fc66e376\transformed\core-1.7.0\res\values\values.xml:105:5-114:25: AAPT: error: resource android:attr/lStar not found.

**Comment by adnanatif** [comment]
found same issue

**Comment by adigujjar** [comment]
@endmr11  please look into this

**Comment by yc424k** [comment]
please look into this

**Comment by Igniscode** [comment]
oh my god same here! why it is not solved until now......
@endmr11

**Comment by endmr11** [comment]
Version 0.0.13 has been released. Could you please check again and report back to me?
