### ISSUE TITLE
There are spelling errors in files

### ISSUE THREAD

**Issue by iCytus** [endmr11/ed_screen_recorder#42]
Hi,
In the file `SwiftEdScreenRecorderPlugin.swift`, on line 123, this should be
`self.videoOutputURL = URL(fileURLWithPath: String(filePath.appendingPathComponent(fileName)))`,
NOT
 `self.videoOutputURL = URL(fileURLWithPath: String(self.filePath.appendingPathComponent(fileName)))`

**Comment by endmr11** [comment]
Version 0.0.13 has been released. Could you please check again and report back to me?

**Comment by iCytus** [comment]
It's useful for me
