### ISSUE TITLE
How do you record certain types of widgets

### ISSUE THREAD

**Issue by JCShareHub** [endmr11/ed_screen_recorder#5]
I have a whiteboard widget with control widgets in a stack.
I'd like to record only the whiteboard widget and then hide the control widgets in the video.

The control widgets must still be displayed to the user when recording but should not reflect in the video

**Current video output:**
![image](https://user-images.githubusercontent.com/105056366/169763944-5c03e090-574b-4e4d-bcf3-d361199d4ca8.png)

**Expected output:**
![image](https://user-images.githubusercontent.com/105056366/169764069-faa548ed-1116-43dc-a5eb-80400f018af9.png)

**Comment by endmr11** [comment]
Our plugin works just like the phone's own native screen recording tool. But the feature you want has been added to our roadmap. I will deal with it as soon as possible.
