### ISSUE TITLE
Audio not being recorded an S21

### ISSUE THREAD

**Issue by rakeshkhoodeeram** [endmr11/ed_screen_recorder#6]
Hello,
I tried the package. Screen is being recorded but with no soun

https://user-images.githubusercontent.com/3471148/170197655-2158e7e8-97d5-460d-929f-d36962308279.mp4

d

**Comment by rakeshkhoodeeram** [comment]
Hi,
Sorry I saw that I had audioEnable: false. I have set it to audioEnable: true.
Even then, I need to go on settings > privacy > permission manager and give Microphone access for the plugin to work.

**Comment by endmr11** [comment]
Ok, thank you for letting me know. It may be more accurate to manage the permission parts with different plugins outside of our plugin like Permission Handler.
