### ISSUE TITLE
permission popup

### ISSUE THREAD

**Issue by cmdbbang** [endmr11/ed_screen_recorder#84]
When recording the screen, a permission popup asking for confirmation appears every time. How can I make it prompt for permission only once, initially?

**Comment by endmr11** [comment]
Use [Permission Handler Package](https://pub.dev/packages/permission_handler)

**Comment by acastry** [comment]
Hi @endmr11  what is the permission in order to handle screen recording ? It is this one that pops up everytime. I think that this permission has been deprecated into Permission Handler Package.
